### PR TITLE
fix modify signature so it actually works, add test, fix update test

### PR DESCRIPTION
**Pull request by intabulas**
This small PR fixes the signature of Modify to take an []Patch vs map[string]any. I have also added a test for Modify to validate the changes. While I was there, I fixed the Update test that would fail

### CODE REVIEW

**Comment by tobiemh** [comment]
@intabulas could you rebase this off of the main branch? I think most instances of `any` have been converted to `interface{}`

**Comment by intabulas** [comment]
I did that last night after the other PR was merged. Let me see ... Oh I see straggling any on the test

**Comment by tobiemh** [comment]
Arggh sorry could you rebase again. The tests have changed.

**Comment by intabulas** [comment]
@tobiemh yeah no worries

**Comment by intabulas** [comment]
@tobiemh rebased

**Comment by tobiemh** [comment]
Apologies for this @intabulas - I've just merged a large PR which has some changes in the `db_test.go` file, which now conflicts. Not too hard to change/rebase I don't think. Then I'll get this merged...

**Comment by intabulas** [comment]
@tobiemh no worries

**Pull request merged**
